"use client";

import React, { useState, useEffect, useCallback } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  ShieldCheck,
  CheckCircle2,
  Clock,
  AlertCircle,
  Sparkles,
  ArrowRight,
  User,
  Phone,
  Mail,
  Layers,
  FileText,
  BadgeCheck,
  ArrowUpRight,
  Send,
  Loader2,
  RefreshCw,
  KeyRound,
  Check,
  CreditCard,
  Ticket as TicketIcon,
  ChevronRight,
  ExternalLink,
  DollarSign,
  AlertTriangle,
} from "lucide-react";

interface Ticket {
  id: string;
  ticketId: string;
  applicationId: string;
  vendorName: string;
  vendorMobile: string;
  vendorEmail?: string;
  currentPlan: string;
  requestedPlan: string;
  reason?: string;
  status: "PENDING" | "AWAITING_PAYMENT" | "PAYMENT_COMPLETED" | "COMPLETED" | "APPROVED" | "REJECTED";
  adminNotes?: string;
  upgradeAmount?: number;
  gatewayFee?: number;
  gstAmount?: number;
  totalAmount?: number;
  paymentStatus?: string;
  paymentId?: string;
  paidAt?: string;
  newUserId?: string;
  newPassword?: string;
  approvedAt?: string;
  createdAt: string;
  updatedAt: string;
}

interface Stats {
  total: number;
  pending: number;
  awaitingPayment: number;
  paymentCompleted: number;
  completed: number;
  rejected: number;
}

export default function AdminTicketsPage() {
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [stats, setStats] = useState<Stats>({
    total: 0,
    pending: 0,
    awaitingPayment: 0,
    paymentCompleted: 0,
    completed: 0,
    rejected: 0,
  });
  const [loading, setLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState<string>("ALL");
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  // Password & Amount editing state for tickets
  const [customPasswords, setCustomPasswords] = useState<Record<string, string>>({});
  const [customUserIds, setCustomUserIds] = useState<Record<string, string>>({});
  const [customUpgradeAmounts, setCustomUpgradeAmounts] = useState<Record<string, number>>({});

  const fetchTickets = useCallback(async () => {
    try {
      setLoading(true);
      const res = await fetch("/api/admin/tickets");
      const data = await res.json();
      if (data.success) {
        setTickets(data.tickets);
        if (data.stats) {
          setStats(data.stats);
        }
      }
    } catch (err: any) {
      setErrorMsg(err.message || "Failed to load tickets");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchTickets();
  }, [fetchTickets]);

  // Stage 1: Approve Plan Change Request
  const handleApprovePlan = async (ticketId: string, upgradeAmt?: number) => {
    try {
      setActionLoading(ticketId);
      setErrorMsg(null);
      setSuccessMsg(null);

      const res = await fetch("/api/admin/tickets", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ticketId,
          action: "approve",
          upgradeAmount: upgradeAmt,
          adminNotes: "Approved by Admin HQ. Vendor must complete tier upgrade payment.",
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || "Failed to approve ticket");
      }

      setSuccessMsg(data.message || `Ticket #${ticketId} approved. Waiting for vendor payment.`);
      fetchTickets();
    } catch (err: any) {
      setErrorMsg(err.message || "Failed to approve ticket");
    } finally {
      setActionLoading(null);
    }
  };

  // Stage 2: Generate & Issue Credentials after payment is completed
  const handleIssueCredentials = async (ticket: Ticket) => {
    try {
      setActionLoading(ticket.ticketId);
      setErrorMsg(null);
      setSuccessMsg(null);

      const pass =
        customPasswords[ticket.ticketId] ||
        `BroomBoom@${ticket.requestedPlan.toUpperCase()}2026`;
      const uid =
        customUserIds[ticket.ticketId] ||
        `BB-${ticket.requestedPlan.toUpperCase()}-${ticket.ticketId.slice(-4)}`;

      const res = await fetch("/api/admin/tickets", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ticketId: ticket.ticketId,
          action: "generate_credentials",
          customUserId: uid,
          customPassword: pass,
          adminNotes: `Payment verified. Upgraded to ${ticket.requestedPlan.toUpperCase()}. New credentials generated by Admin HQ.`,
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || "Failed to issue credentials");
      }

      setSuccessMsg(data.message || `Credentials issued for #${ticket.ticketId}!`);
      fetchTickets();
    } catch (err: any) {
      setErrorMsg(err.message || "Failed to issue credentials");
    } finally {
      setActionLoading(null);
    }
  };

  // Reject ticket
  const handleRejectTicket = async (ticketId: string) => {
    if (!confirm(`Are you sure you want to reject ticket #${ticketId}?`)) return;
    try {
      setActionLoading(ticketId);
      setErrorMsg(null);
      const res = await fetch("/api/admin/tickets", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ticketId,
          action: "reject",
          adminNotes: "Plan change request rejected by HQ Operations.",
        }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) throw new Error(data.error);
      setSuccessMsg(`Ticket #${ticketId} rejected.`);
      fetchTickets();
    } catch (err: any) {
      setErrorMsg(err.message);
    } finally {
      setActionLoading(null);
    }
  };

  const filteredTickets = tickets.filter((t) => {
    if (activeFilter === "ALL") return true;
    if (activeFilter === "PENDING") return t.status === "PENDING";
    if (activeFilter === "AWAITING_PAYMENT") return t.status === "AWAITING_PAYMENT";
    if (activeFilter === "PAYMENT_COMPLETED") return t.status === "PAYMENT_COMPLETED";
    if (activeFilter === "COMPLETED") return t.status === "COMPLETED" || t.status === "APPROVED";
    return true;
  });

  return (
    <div className="min-h-screen bg-slate-100 text-slate-900 font-sans">
      {/* Top Header */}
      <header className="bg-slate-950 text-white border-b border-slate-800 sticky top-0 z-30 px-4 sm:px-8 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="relative w-10 h-10 rounded-full overflow-hidden border-2 border-amber-400">
              <Image src="/broomboom-logo.png" alt="BroomBoom" fill className="object-cover" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-lg font-black tracking-tight">
                  Broom<span className="text-amber-400">Boom</span>
                </span>
                <span className="bg-amber-400/20 text-amber-300 text-[10px] font-black px-2 py-0.5 rounded border border-amber-400/30 uppercase">
                  Admin HQ
                </span>
              </div>
              <p className="text-[11px] text-slate-400">Plan Change &amp; Support Ticket Management Desk</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={fetchTickets}
              disabled={loading}
              className="flex items-center gap-1.5 text-xs font-bold text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 px-3.5 py-2 rounded-xl transition-all cursor-pointer"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
              <span>Refresh</span>
            </button>

            <Link
              href="/vendor/dashboard"
              target="_blank"
              className="flex items-center gap-1.5 text-xs font-bold text-slate-950 bg-amber-400 hover:bg-amber-300 px-3.5 py-2 rounded-xl transition-all shadow-sm"
            >
              <span>View Vendor Dashboard</span>
              <ExternalLink className="w-3.5 h-3.5" />
            </Link>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="max-w-7xl mx-auto px-4 sm:px-8 py-8 space-y-6">
        {/* Banner Alert Messages */}
        {errorMsg && (
          <div className="p-4 bg-rose-50 border border-rose-200 rounded-2xl text-rose-900 text-xs font-semibold flex items-center justify-between">
            <div className="flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0" />
              <span>{errorMsg}</span>
            </div>
            <button onClick={() => setErrorMsg(null)} className="text-rose-500 font-bold hover:text-rose-700">
              &times;
            </button>
          </div>
        )}

        {successMsg && (
          <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-2xl text-emerald-950 text-xs font-bold flex items-center justify-between shadow-xs">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
              <span>{successMsg}</span>
            </div>
            <button onClick={() => setSuccessMsg(null)} className="text-emerald-700 font-bold hover:text-emerald-900">
              &times;
            </button>
          </div>
        )}

        {/* Workflow Explanation Helper Banner */}
        <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white rounded-3xl p-6 shadow-md border border-slate-800 space-y-3">
          <div className="flex items-center gap-2 text-amber-400 text-xs font-extrabold uppercase tracking-wider">
            <Sparkles className="w-4 h-4" />
            2-Stage Plan Upgrade &amp; Credential Protocol
          </div>
          <h2 className="text-xl sm:text-2xl font-black">Plan Change Operations Workflow</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs pt-1">
            <div className="bg-white/10 p-3.5 rounded-2xl border border-white/10 space-y-1">
              <strong className="text-amber-300 block">Step 1: Admin Approves Request</strong>
              <p className="text-slate-300 text-[11px] leading-relaxed">
                When a partner requests an upgrade (e.g. Silver &rarr; Gold), Admin clicks <strong>Approve Plan</strong>. The fee difference is calculated, and the <strong>Pay Now</strong> button appears on the vendor dashboard.
              </p>
            </div>
            <div className="bg-white/10 p-3.5 rounded-2xl border border-white/10 space-y-1">
              <strong className="text-cyan-300 block">Step 2: Vendor Pays Upgrade Fee</strong>
              <p className="text-slate-300 text-[11px] leading-relaxed">
                The partner logs in to their dashboard and clicks <strong>Pay Now</strong>. Once paid, the ticket automatically moves to <strong>Payment Completed</strong> for final Admin review.
              </p>
            </div>
            <div className="bg-white/10 p-3.5 rounded-2xl border border-white/10 space-y-1">
              <strong className="text-emerald-300 block">Step 3: Admin Issues New Password</strong>
              <p className="text-slate-300 text-[11px] leading-relaxed">
                Admin verifies the payment and clicks <strong>Generate &amp; Issue Credentials</strong>. The partner is issued their new User ID and Password, and the upgraded plan activates.
              </p>
            </div>
          </div>
        </div>

        {/* Statistics Metric Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
          <button
            onClick={() => setActiveFilter("ALL")}
            className={`p-4 rounded-2xl border text-left transition-all cursor-pointer ${
              activeFilter === "ALL"
                ? "bg-slate-900 text-white border-slate-950 shadow-md"
                : "bg-white text-slate-800 border-slate-200 hover:bg-slate-50"
            }`}
          >
            <span className="text-[10px] font-bold uppercase tracking-wider block opacity-70">Total Tickets</span>
            <span className="text-2xl font-black">{stats.total}</span>
          </button>

          <button
            onClick={() => setActiveFilter("PENDING")}
            className={`p-4 rounded-2xl border text-left transition-all cursor-pointer ${
              activeFilter === "PENDING"
                ? "bg-amber-500 text-slate-950 border-amber-600 shadow-md font-black"
                : "bg-white text-slate-800 border-slate-200 hover:bg-amber-50/50"
            }`}
          >
            <span className="text-[10px] font-bold uppercase tracking-wider block opacity-70">1. Pending Review</span>
            <span className="text-2xl font-black text-amber-600">{stats.pending}</span>
          </button>

          <button
            onClick={() => setActiveFilter("AWAITING_PAYMENT")}
            className={`p-4 rounded-2xl border text-left transition-all cursor-pointer ${
              activeFilter === "AWAITING_PAYMENT"
                ? "bg-blue-600 text-white border-blue-700 shadow-md"
                : "bg-white text-slate-800 border-slate-200 hover:bg-blue-50/50"
            }`}
          >
            <span className="text-[10px] font-bold uppercase tracking-wider block opacity-70">2. Awaiting Payment</span>
            <span className="text-2xl font-black text-blue-600">{stats.awaitingPayment}</span>
          </button>

          <button
            onClick={() => setActiveFilter("PAYMENT_COMPLETED")}
            className={`p-4 rounded-2xl border text-left transition-all cursor-pointer ${
              activeFilter === "PAYMENT_COMPLETED"
                ? "bg-purple-600 text-white border-purple-700 shadow-md"
                : "bg-white text-slate-800 border-slate-200 hover:bg-purple-50/50"
            }`}
          >
            <span className="text-[10px] font-bold uppercase tracking-wider block opacity-70">3. Paid (Issue Pass)</span>
            <span className="text-2xl font-black text-purple-600">{stats.paymentCompleted}</span>
          </button>

          <button
            onClick={() => setActiveFilter("COMPLETED")}
            className={`p-4 rounded-2xl border text-left transition-all cursor-pointer ${
              activeFilter === "COMPLETED"
                ? "bg-emerald-600 text-white border-emerald-700 shadow-md"
                : "bg-white text-slate-800 border-slate-200 hover:bg-emerald-50/50"
            }`}
          >
            <span className="text-[10px] font-bold uppercase tracking-wider block opacity-70">4. Completed</span>
            <span className="text-2xl font-black text-emerald-600">{stats.completed}</span>
          </button>
        </div>

        {/* Tickets List */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200 shadow-sm space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-4">
            <div>
              <h3 className="text-xl font-black text-slate-950 flex items-center gap-2">
                <TicketIcon className="w-5 h-5 text-amber-600" />
                Plan Change Tickets ({filteredTickets.length})
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Showing: <strong className="uppercase">{activeFilter}</strong> requests
              </p>
            </div>

            {/* Filter Pills */}
            <div className="flex items-center gap-1.5 overflow-x-auto pb-1">
              {[
                { id: "ALL", label: "All" },
                { id: "PENDING", label: `Pending (${stats.pending})` },
                { id: "AWAITING_PAYMENT", label: `Awaiting Pay (${stats.awaitingPayment})` },
                { id: "PAYMENT_COMPLETED", label: `Paid / Action Needed (${stats.paymentCompleted})` },
                { id: "COMPLETED", label: `Completed (${stats.completed})` },
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveFilter(tab.id)}
                  className={`text-xs font-bold px-3 py-1.5 rounded-xl whitespace-nowrap transition-all cursor-pointer ${
                    activeFilter === tab.id
                      ? "bg-slate-900 text-white font-black"
                      : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>
          </div>

          {loading ? (
            <div className="py-16 flex flex-col items-center justify-center space-y-3">
              <Loader2 className="w-8 h-8 text-amber-500 animate-spin" />
              <p className="text-xs font-bold text-slate-500">Loading tickets database...</p>
            </div>
          ) : filteredTickets.length === 0 ? (
            <div className="py-14 text-center bg-slate-50 rounded-2xl border border-dashed border-slate-300 space-y-2">
              <TicketIcon className="w-8 h-8 text-slate-400 mx-auto" />
              <h4 className="text-sm font-bold text-slate-700">No Tickets in this category</h4>
              <p className="text-xs text-slate-400">All caught up or switch filter above.</p>
            </div>
          ) : (
            <div className="space-y-5">
              {filteredTickets.map((t) => {
                const isPending = t.status === "PENDING";
                const isAwaitingPay = t.status === "AWAITING_PAYMENT";
                const isPaid = t.status === "PAYMENT_COMPLETED";
                const isCompleted = t.status === "COMPLETED" || t.status === "APPROVED";

                // Calculations
                const getBase = (tier: string) =>
                  tier === "silver" ? 10000 : tier === "platinum" ? 50000 : 20000;
                const currBase = getBase(t.currentPlan.toLowerCase());
                const newBase = getBase(t.requestedPlan.toLowerCase());
                const defaultUpgrade = newBase > currBase ? newBase - currBase : newBase;
                const activeUpgradeAmt =
                  customUpgradeAmounts[t.ticketId] !== undefined
                    ? customUpgradeAmounts[t.ticketId]
                    : defaultUpgrade;
                const calcTotal = Math.round(activeUpgradeAmt * 1.08);

                return (
                  <div
                    key={t.id}
                    className={`rounded-2xl p-6 border transition-all ${
                      isPaid
                        ? "bg-purple-50/60 border-purple-300 shadow-md ring-2 ring-purple-400/20"
                        : isPending
                        ? "bg-amber-50/50 border-amber-300"
                        : isAwaitingPay
                        ? "bg-blue-50/50 border-blue-300"
                        : "bg-slate-50/80 border-slate-200"
                    }`}
                  >
                    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-6">
                      {/* Left: Partner & Ticket Details */}
                      <div className="space-y-3 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <code className="font-mono font-black text-xs bg-white px-2.5 py-1 rounded border border-slate-200 text-slate-900 shadow-2xs">
                            #{t.ticketId}
                          </code>
                          <span
                            className={`text-[10px] font-black uppercase px-3 py-1 rounded-full border ${
                              isPaid
                                ? "bg-purple-100 text-purple-950 border-purple-300 animate-pulse"
                                : isPending
                                ? "bg-amber-100 text-amber-950 border-amber-300"
                                : isAwaitingPay
                                ? "bg-blue-100 text-blue-950 border-blue-300"
                                : isCompleted
                                ? "bg-emerald-100 text-emerald-950 border-emerald-300"
                                : "bg-slate-200 text-slate-800"
                            }`}
                          >
                            {isPaid
                              ? "★ Payment Received — Issue Password Now"
                              : isPending
                              ? "Needs Admin Approval"
                              : isAwaitingPay
                              ? "Waiting for Vendor to Pay"
                              : isCompleted
                              ? "Active & Completed"
                              : t.status}
                          </span>
                          <span className="text-xs text-slate-500 font-medium">
                            Created: {new Date(t.createdAt).toLocaleString()}
                          </span>
                        </div>

                        {/* Partner Contact Card */}
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs bg-white p-3.5 rounded-xl border border-slate-200/80 shadow-2xs">
                          <div>
                            <span className="text-[10px] font-bold text-slate-400 uppercase block">Partner Name</span>
                            <strong className="text-slate-900 text-sm block">{t.vendorName}</strong>
                            <span className="text-[11px] font-mono text-slate-500">{t.applicationId}</span>
                          </div>
                          <div>
                            <span className="text-[10px] font-bold text-slate-400 uppercase block">Mobile Number</span>
                            <a href={`tel:${t.vendorMobile}`} className="font-bold text-slate-900 hover:text-amber-600 block">
                              {t.vendorMobile}
                            </a>
                            <span className="text-[10px] text-slate-500">{t.vendorEmail || "No email"}</span>
                          </div>
                          <div>
                            <span className="text-[10px] font-bold text-slate-400 uppercase block">Plan Change Requested</span>
                            <div className="font-black text-sm">
                              <span className="uppercase text-slate-600">{t.currentPlan}</span>
                              <span className="mx-1 text-slate-400">&rarr;</span>
                              <span className="uppercase text-amber-700 underline font-black">{t.requestedPlan}</span>
                            </div>
                          </div>
                        </div>

                        {/* Reason & Notes */}
                        <div className="text-xs space-y-1">
                          <p className="text-slate-700">
                            <strong>Partner Reason:</strong> {t.reason || "Tier upgrade request"}
                          </p>
                          {t.adminNotes && (
                            <div className="text-[11px] text-slate-700 bg-white/80 p-2.5 rounded-xl border border-slate-200">
                              <strong>Admin Log:</strong> {t.adminNotes}
                            </div>
                          )}
                        </div>

                        {/* If Completed, show credentials */}
                        {isCompleted && t.newUserId && (
                          <div className="bg-emerald-100/90 border border-emerald-300 rounded-xl p-3 flex flex-wrap items-center justify-between gap-2 text-xs text-emerald-950 font-bold">
                            <div className="flex items-center gap-2">
                              <KeyRound className="w-4 h-4 text-emerald-700" />
                              <span>
                                Active User ID: <code className="font-mono font-black">{t.newUserId}</code> | Password: <code className="font-mono font-black">{t.newPassword}</code>
                              </span>
                            </div>
                            <span className="text-[10px] uppercase font-extrabold bg-white px-2 py-0.5 rounded border border-emerald-200">
                              Dispatched via WhatsApp / Email
                            </span>
                          </div>
                        )}
                      </div>

                      {/* Right: Action Panel based on Stage */}
                      <div className="lg:w-80 shrink-0 space-y-3">
                        {/* STAGE 1: PENDING -> ADMIN APPROVES */}
                        {isPending && (
                          <div className="bg-white p-4 rounded-2xl border border-amber-300 shadow-sm space-y-3">
                            <span className="text-[10px] font-black uppercase text-amber-900 block">
                              Stage 1: Admin Plan Review
                            </span>
                            <div className="bg-amber-50 p-3 rounded-xl border border-amber-200 text-xs space-y-2">
                              <div className="flex justify-between font-medium text-slate-600">
                                <span>Suggested Base:</span>
                                <span>₹{defaultUpgrade.toLocaleString("en-IN")}</span>
                              </div>
                              <div className="space-y-1">
                                <label className="text-[10px] font-bold text-amber-900 block">
                                  Approved Base Fee (₹):
                                </label>
                                <input
                                  type="number"
                                  value={activeUpgradeAmt}
                                  onChange={(e) =>
                                    setCustomUpgradeAmounts((prev) => ({
                                      ...prev,
                                      [t.ticketId]: Math.max(0, parseInt(e.target.value) || 0),
                                    }))
                                  }
                                  className="w-full text-xs font-mono font-bold bg-white border border-amber-300 rounded-lg px-2.5 py-1.5 text-slate-900 focus:outline-none focus:border-amber-500"
                                />
                              </div>
                              <div className="flex justify-between font-black text-amber-950 border-t border-amber-200 pt-1 text-sm">
                                <span>Total Payable (incl 8%):</span>
                                <span>₹{calcTotal.toLocaleString("en-IN")}</span>
                              </div>
                            </div>

                            <button
                              type="button"
                              onClick={() => handleApprovePlan(t.ticketId, activeUpgradeAmt)}
                              disabled={actionLoading === t.ticketId}
                              className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs py-2.5 rounded-xl shadow-xs transition-all flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
                            >
                              {actionLoading === t.ticketId ? (
                                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                              ) : (
                                <Check className="w-4 h-4 stroke-[3]" />
                              )}
                              <span>Approve &amp; Request Payment (₹{calcTotal.toLocaleString("en-IN")})</span>
                            </button>

                            <button
                              type="button"
                              onClick={() => handleRejectTicket(t.ticketId)}
                              disabled={actionLoading === t.ticketId}
                              className="w-full bg-rose-50 hover:bg-rose-100 text-rose-700 font-bold text-xs py-2 rounded-xl transition-all cursor-pointer"
                            >
                              Reject Request
                            </button>
                          </div>
                        )}

                        {/* STAGE 2: AWAITING PAYMENT */}
                        {isAwaitingPay && (
                          <div className="bg-white p-4 rounded-2xl border border-blue-200 shadow-sm space-y-2.5 text-xs text-slate-700">
                            <span className="text-[10px] font-black uppercase text-blue-900 block">
                              Stage 2: Waiting for Vendor Payment
                            </span>
                            <div className="bg-blue-50 p-3 rounded-xl border border-blue-200 space-y-1">
                              <span className="text-[10px] text-blue-800 font-bold uppercase block">
                                Approved Amount:
                              </span>
                              <span className="text-xl font-black text-blue-950 block">
                                ₹{(t.totalAmount || calcTotal).toLocaleString("en-IN")}
                              </span>
                              <p className="text-[11px] text-blue-800 pt-1">
                                Vendor has been notified. The <strong>Pay Now</strong> button is active on their dashboard.
                              </p>
                            </div>
                          </div>
                        )}

                        {/* STAGE 3: PAYMENT COMPLETED -> ADMIN GENERATES CREDENTIALS */}
                        {isPaid && (
                          <div className="bg-white p-4 rounded-2xl border-2 border-purple-400 shadow-lg space-y-3">
                            <div className="flex items-center gap-1.5 text-purple-950 font-black text-xs">
                              <Sparkles className="w-4 h-4 text-purple-600" />
                              <span>Stage 3: Issue New Credentials</span>
                            </div>

                            <div className="bg-purple-50 p-2.5 rounded-xl border border-purple-200 text-xs space-y-0.5">
                              <span className="text-[10px] font-bold text-purple-800 uppercase block">
                                Verified Payment Received:
                              </span>
                              <span className="text-lg font-black text-purple-950">
                                ₹{(t.totalAmount || calcTotal).toLocaleString("en-IN")}
                              </span>
                              <span className="text-[10px] text-slate-500 block">
                                Ref: {t.paymentId || "CF_VERIFIED"}
                              </span>
                            </div>

                            {/* Password Input / Generator */}
                            <div className="space-y-1">
                              <label className="text-[10px] font-bold text-slate-600 block">
                                Set Vendor Password:
                              </label>
                              <input
                                type="text"
                                value={
                                  customPasswords[t.ticketId] ??
                                  `BroomBoom@${t.requestedPlan.toUpperCase()}2026`
                                }
                                onChange={(e) =>
                                  setCustomPasswords((prev) => ({
                                    ...prev,
                                    [t.ticketId]: e.target.value,
                                  }))
                                }
                                className="w-full text-xs font-mono font-bold bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-slate-900 focus:outline-none focus:border-purple-500"
                              />
                            </div>

                            <button
                              type="button"
                              onClick={() => handleIssueCredentials(t)}
                              disabled={actionLoading === t.ticketId}
                              className="w-full bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white font-black text-xs py-2.5 rounded-xl shadow-md transition-all flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
                            >
                              {actionLoading === t.ticketId ? (
                                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                              ) : (
                                <KeyRound className="w-4 h-4" />
                              )}
                              <span>Generate &amp; Send New Password</span>
                            </button>
                          </div>
                        )}

                        {/* STAGE 4: COMPLETED */}
                        {isCompleted && (
                          <div className="bg-emerald-50 p-4 rounded-2xl border border-emerald-200 text-xs text-emerald-950 space-y-1">
                            <span className="text-[10px] font-black uppercase text-emerald-800 block">
                              Completed &amp; Active
                            </span>
                            <div className="font-extrabold text-sm">Plan Upgraded Successfully</div>
                            <p className="text-[11px] text-emerald-800 leading-relaxed">
                              Partner credentials issued. Territory scope and subscription terms updated.
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

